-- Schema for Daily Pulse core tables

-- Enum for post draft status
DO $$ BEGIN
  CREATE TYPE post_status AS ENUM ('draft', 'ready', 'published', 'scheduled');
EXCEPTION
  WHEN duplicate_object THEN null;
END $$;

-- profiles extends auth.users
CREATE TABLE IF NOT EXISTS profiles (
  id uuid PRIMARY KEY REFERENCES auth.users(id),
  full_name text,
  role text,
  sector text,
  objective text,
  language text DEFAULT 'it',
  brand_palette text,
  linkedin_access_token text,
  created_at timestamptz DEFAULT timezone('utc', now()),
  updated_at timestamptz DEFAULT timezone('utc', now())
);

-- topics associated with a user and day of week
CREATE TABLE IF NOT EXISTS topics (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  title text NOT NULL,
  day_of_week int2 NOT NULL CHECK (day_of_week >= 0 AND day_of_week <= 6),
  is_active boolean DEFAULT true,
  created_at timestamptz DEFAULT timezone('utc', now()),
  updated_at timestamptz DEFAULT timezone('utc', now())
);

-- insights table
CREATE TABLE IF NOT EXISTS insights (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  topic_id uuid REFERENCES topics(id) ON DELETE SET NULL,
  title text NOT NULL,
  url text NOT NULL,
  source text NOT NULL,
  published_date date,
  summary_bullets text[] NOT NULL,
  content text,
  pulse_score int2 NOT NULL,
  created_at timestamptz DEFAULT timezone('utc', now())
);

-- post drafts generated by Ghostwriter
CREATE TABLE IF NOT EXISTS post_drafts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  topic_id uuid REFERENCES topics(id) ON DELETE SET NULL,
  insight_ids uuid[] DEFAULT ARRAY[]::uuid[],
  generated_text text NOT NULL,
  edited_text text,
  status post_status DEFAULT 'draft',
  linkedin_post_id text,
  created_at timestamptz DEFAULT timezone('utc', now()),
  updated_at timestamptz DEFAULT timezone('utc', now())
);

-- trigger to update updated_at on post_drafts
CREATE OR REPLACE FUNCTION update_post_drafts_modtime()
RETURNS trigger AS $$
BEGIN
  NEW.updated_at = timezone('utc', now());
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS post_drafts_set_updated_at ON post_drafts;
CREATE TRIGGER post_drafts_set_updated_at
BEFORE UPDATE ON post_drafts
FOR EACH ROW EXECUTE PROCEDURE update_post_drafts_modtime();

-- image assets linked to drafts
CREATE TABLE IF NOT EXISTS image_assets (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  draft_id uuid REFERENCES post_drafts(id) ON DELETE CASCADE,
  url text NOT NULL,
  description text,
  created_at timestamptz DEFAULT timezone('utc', now())
);

-- analytics snapshots for published posts
CREATE TABLE IF NOT EXISTS analytics_snapshots (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  draft_id uuid REFERENCES post_drafts(id) ON DELETE SET NULL,
  linkedin_post_id text,
  impressions int DEFAULT 0,
  likes int DEFAULT 0,
  comments int DEFAULT 0,
  shares int DEFAULT 0,
  captured_at timestamptz DEFAULT timezone('utc', now())
);

-- Indexes to optimize lookups
CREATE INDEX IF NOT EXISTS idx_topics_user_day ON topics(user_id, day_of_week) WHERE is_active;
CREATE INDEX IF NOT EXISTS idx_insights_user ON insights(user_id);
CREATE INDEX IF NOT EXISTS idx_post_drafts_user ON post_drafts(user_id);
